/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dataPemohonForm.java
 *
 * Created on 03 Okt 13, 23:37:48
 */

package ADMIN;

import Controller.PemohonController;
import Entity.DataPemohon;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class dataPemohonForm extends javax.swing.JPanel {
    PemohonController upd;
List<DataPemohon> records = new ArrayList<DataPemohon>();

    /** Creates new form dataPemohonForm */
    public dataPemohonForm() {

        initComponents();
        upd = new PemohonController();
        this.statusAwal();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nkkLabel = new javax.swing.JLabel();
        namaKepalaKeluargaLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        rtrwLabel = new javax.swing.JLabel();
        desaLabel = new javax.swing.JLabel();
        nkkTF = new javax.swing.JTextField();
        namaKepalaKeluargaTF = new javax.swing.JTextField();
        alamatTF = new javax.swing.JTextField();
        rtrwTF = new javax.swing.JTextField();
        desaTF = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pemohonTabel = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(800, 458));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setBackground(new java.awt.Color(204, 153, 255));
        jLabel1.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("INPUT DATA PEMOHON");

        nkkLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        nkkLabel.setForeground(new java.awt.Color(0, 0, 51));
        nkkLabel.setText("NKK");

        namaKepalaKeluargaLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        namaKepalaKeluargaLabel.setForeground(new java.awt.Color(0, 0, 51));
        namaKepalaKeluargaLabel.setText("NAMA KEPALA KELUARGA");

        alamatLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        alamatLabel.setForeground(new java.awt.Color(0, 0, 51));
        alamatLabel.setText("ALAMAT");

        rtrwLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rtrwLabel.setForeground(new java.awt.Color(0, 0, 51));
        rtrwLabel.setText("RT/RW");

        desaLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        desaLabel.setForeground(new java.awt.Color(0, 0, 51));
        desaLabel.setText("DESA");

        nkkTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nkkTFActionPerformed(evt);
            }
        });

        namaKepalaKeluargaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKepalaKeluargaTFActionPerformed(evt);
            }
        });

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaKepalaKeluargaLabel)
                    .addComponent(nkkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatLabel)
                    .addComponent(rtrwLabel)
                    .addComponent(desaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(50, 50, 50)
                        .addComponent(editButton)
                        .addGap(41, 41, 41)
                        .addComponent(deleteButton))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nkkTF)
                        .addComponent(namaKepalaKeluargaTF)
                        .addComponent(alamatTF)
                        .addComponent(rtrwTF)
                        .addComponent(desaTF, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(274, 274, 274))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nkkLabel)
                    .addComponent(nkkTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaKepalaKeluargaLabel)
                    .addComponent(namaKepalaKeluargaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamatLabel)
                    .addComponent(alamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtrwLabel)
                    .addComponent(rtrwTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desaLabel)
                    .addComponent(desaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pemohonTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NKK", "NAMA KEPALA KELUARGA", "ALAMAT", "RT/RW", "DESA"
            }
        ));
        pemohonTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pemohonTabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pemohonTabel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nkkTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nkkTFActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nkkTFActionPerformed

    private void namaKepalaKeluargaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKepalaKeluargaTFActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_namaKepalaKeluargaTFActionPerformed

    void isiTabel() {
        Object data[][] = new Object[records.size()][6];
        int x = 0;
        for (DataPemohon b : records) {
            data[x][0] = b.getNKK();
            data[x][1] = b.getNama_kepala_keluarga();
            data[x][2] = b.getAlamat();
            data[x][3] = b.getRt_rw();
            data[x][4] = b.getDesa();
            x++;
        }
        String judul[] = {"nkk ", "Nama", "alamat", "rtrw", "desa"};
        pemohonTabel.setModel(new DefaultTableModel(data, judul));
}

    void loadBarang() {
        try {
            records = upd.getAll();
        } catch (SQLException ex) {
            Logger.getLogger(dataPemohonForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void statusAwal() {
        this.loadBarang();
        this.isiTabel();

    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try {
            String nkk = nkkTF.getText();
            String nama = namaKepalaKeluargaTF.getText();
            String alamat = alamatTF.getText();
            String rtrw = rtrwTF.getText();
            String desa = desaTF.getText();

            DataPemohon baru = new DataPemohon();
            baru.setNKK(nkk);
            baru.setNama_kepala_keluarga(nama);
            baru.setAlamat(alamat);
            baru.setRt_rw(rtrw);
            baru.setDesa(desa);

            PemohonController pemkon = PemohonController.getPemohonKontrol();
            pemkon.insertData(baru);
       

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
            this.statusAwal();

        } catch (SQLException ex) {
            Logger.getLogger(dataPemohonForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Data gagal disimpan");
        }
}//GEN-LAST:event_saveButtonActionPerformed

    private void pemohonTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemohonTabelMouseClicked
        // TODO add your handling code here:
         int row = pemohonTabel.getSelectedRow();
        String nkk = pemohonTabel.getValueAt(row, 0).toString();
        String namakepala = pemohonTabel.getValueAt(row, 1).toString();
        String alamat = pemohonTabel.getValueAt(row, 2).toString();
        String rtrw = pemohonTabel.getValueAt(row, 3).toString();
        String desa = pemohonTabel.getValueAt(row, 4).toString();

        nkkTF.setText(nkk);
        namaKepalaKeluargaTF.setText(namakepala);
        alamatTF.setText(alamat);
        rtrwTF.setText(rtrw);
        desaTF.setText(desa);

       nkkTF.requestFocus();
        namaKepalaKeluargaTF.requestFocus();
        alamatTF.requestFocus();
        rtrwTF.requestFocus();
        desaTF.requestFocus();

//        hapusButton.setEnabled(true);
//        ubahButton.setEnabled(true);
//        batalButton.setEnabled(true);
    }//GEN-LAST:event_pemohonTabelMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
         try {
         String nkk = nkkTF.getText();
            String nama = namaKepalaKeluargaTF.getText();
            String alamat = alamatTF.getText();
            String rtrw = rtrwTF.getText();
            String desa = desaTF.getText();

        DataPemohon d = new DataPemohon();
       d.setNKK(nkk);
       d.setNama_kepala_keluarga(nama);
       d.setAlamat(alamat);
       d.setRt_rw(rtrw);
       d.setDesa(desa);

         PemohonController pemkon = PemohonController.getPemohonKontrol();
       pemkon.updtaeData(d);

        JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            this.statusAwal();

        } catch (SQLException ex) {
            Logger.getLogger(dataPemohonForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Data gagal diubah");
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        try{
          String nkk = nkkTF.getText();


        DataPemohon d = new DataPemohon();
       d.setNKK(nkk);


      PemohonController pemkon = PemohonController.getPemohonKontrol();
      pemkon.deleteData(d);
       JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
            this.statusAwal();

        } catch (SQLException ex) {
            Logger.getLogger(dataPemohonForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Data gagal dihapus");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextField alamatTF;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel desaLabel;
    private javax.swing.JTextField desaTF;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel namaKepalaKeluargaLabel;
    private javax.swing.JTextField namaKepalaKeluargaTF;
    private javax.swing.JLabel nkkLabel;
    private javax.swing.JTextField nkkTF;
    private javax.swing.JTable pemohonTabel;
    private javax.swing.JLabel rtrwLabel;
    private javax.swing.JTextField rtrwTF;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

}
