/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import Entity.DataPemohon;
import Entity.KriteriaWarga;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author fendi
 */
public class DetailPemohonDialog extends javax.swing.JDialog {
    private DataPemohon dataPemohon;
    /**
     * Creates new form DetailPemohon
     */
    public DetailPemohonDialog(DataPemohon dataPemohon,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.dataPemohon=dataPemohon;
        this.setTitle("Detail variabel data pemohon: "+dataPemohon.getNama_kepala_keluarga()+" "+dataPemohon.getNKK());
        DetailDataPemohonTableModel detailDataPemohonTableModel=new DetailDataPemohonTableModel(dataPemohon.getKriteriaWargaList());
        detailTabel.setModel(detailDataPemohonTableModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        detailTabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        detailTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(detailTabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable detailTabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    class DetailDataPemohonTableModel extends AbstractTableModel{
        private List<KriteriaWarga> kwList;
        public DetailDataPemohonTableModel(List<KriteriaWarga> kwList){
            this.kwList=kwList;
        }
        public int getRowCount() {
            return kwList.size();
        }

        @Override
        public String getColumnName(int column) {
            return column==0?"Kriteria":"Isi";
        }

        public int getColumnCount() {
            return 2;
        }

        public Object getValueAt(int row, int column) {
             switch (column) {
                case 0: return kwList.get(row).getKriteria().getNama_kriteria();
                case 1: return kwList.get(row).getNamaSubkriteria();
                default: return "";
              }
        }
        
    }

}
