/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HalamanSimulasi1.java
 *
 * Created on 09 Okt 13, 10:26:16
 */

package ADMIN;

import Controller.KriteriaController;
import Controller.PemohonController;
import Entity.DataPemohon;
import Entity.DataPemohonSAW;
import Entity.Kriteria;
import LOGIN.HalamanUtamaForm1;
import TableModel.DataPemohonKriteriaTableModel;
import TableModel.DataPenerimaTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class HalamanSimulasi1 extends javax.swing.JPanel {
    List<DataPemohon> dataPemohonList,dataPenerimaList;
    List<Kriteria> kriteriaList;
    PemohonController pemohonController;
    KriteriaController kriteriaController;
    DataPemohonSAW dataPemohonSAW;
    HalamanUtamaForm1 halamanUtama;
    final double 
            RENDAH_MIN=0,RENDAH_MAKS=2.99,
            SEDANG_MIN=3.00,SEDANG_MAKS=4.99,
            TINGGI_MIN=5.00,TINGGI_MAKS=6.99
            ;
    /** Creates new form HalamanSimulasi1 */
//    public HalamanSimulasi1() {
////         initComponents();
//    }
    public HalamanSimulasi1(HalamanUtamaForm1 halamanUtama) {
        initComponents();
        this.halamanUtama=halamanUtama;
        rendahLabel.setText("Rendah "+RENDAH_MIN+" - "+RENDAH_MAKS);
        sedangLabel.setText("Sedang "+SEDANG_MIN+" - "+SEDANG_MAKS);
        tinggiLabel.setText("Tinggi "+TINGGI_MIN+" - "+TINGGI_MAKS);
        try {
            pemohonController=PemohonController.getPemohonKontrol();
            kriteriaController=KriteriaController.getKriteriaKontrol();
        } catch (SQLException ex) {
            Logger.getLogger(HalamanSimulasi1.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            kriteriaList=kriteriaController.getAllKriteria();
            dataPemohonList=pemohonController.getAllWithKriteria();
            
        } catch (SQLException ex) {
            Logger.getLogger(HalamanSimulasi1.class.getName()).log(Level.SEVERE, null, ex);
        }
        processSAW();
    }

    

  

 
    private void processSAW(){
        dataPemohonSAW=new DataPemohonSAW(dataPemohonList,kriteriaList);
        DataPemohonKriteriaTableModel dataPemohonKriteriaTableModel=new DataPemohonKriteriaTableModel(dataPemohonSAW.getDataPemohonOrdered(), kriteriaList);
        jTable1.setModel(dataPemohonKriteriaTableModel);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rendahLabel = new javax.swing.JLabel();
        sedangLabel = new javax.swing.JLabel();
        tinggiLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patokanSkorText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        penerimaTabel = new javax.swing.JTable();
        tutupButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIMULASI DATA PEMOHON");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", ""},
                {"", "", "", "", ""},
                {"", "", "", "", ""},
                {"", "", "", "", null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Kriteria 1", "Kriteria 2", "Kriteria 3", "Skor"
            }
        ));
        jTable1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTable1);

        rendahLabel.setText("jLabel4");

        sedangLabel.setText("jLabel5");

        tinggiLabel.setText("jLabel6");

        jLabel7.setText("Keterangan");

        jLabel3.setText("Patokan Skor");

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tinggiLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(sedangLabel))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rendahLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patokanSkorText, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rendahLabel)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(patokanSkorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sedangLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tinggiLabel)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HASIL PENERIMA JAMKESDA");

        penerimaTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NKK", "Nama Kepala Keluarga", "Alamat", "Hasil Keputusan"
            }
        ));
        penerimaTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penerimaTabelMouseClicked(evt);
            }
        });
        penerimaTabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                penerimaTabelKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(penerimaTabel);

        tutupButton.setText("TUTUP");
        tutupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 696, Short.MAX_VALUE)
                                .addComponent(tutupButton)
                                .addGap(19, 19, 19)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(tutupButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tutupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupButtonActionPerformed

}//GEN-LAST:event_tutupButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double patokanSkor=0;
        try{
            patokanSkor= Double.valueOf(patokanSkorText.getText());
        }catch(Exception e){
            new JOptionPane("Inputan harus angka").show();
        }
        dataPenerimaList=new ArrayList<DataPemohon>();
        dataPenerimaList=dataPemohonSAW.getDataPemohonOrdered();
        DataPenerimaTableModel dataPenerimaTableModel=new DataPenerimaTableModel(dataPenerimaList,patokanSkor);
        penerimaTabel.setModel(dataPenerimaTableModel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void penerimaTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penerimaTabelMouseClicked
        DetailPemohonDialog dialog = new DetailPemohonDialog(dataPenerimaList.get(penerimaTabel.getSelectedRow()),
                halamanUtama, true);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_penerimaTabelMouseClicked

    private void penerimaTabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_penerimaTabelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_penerimaTabelKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField patokanSkorText;
    private javax.swing.JTable penerimaTabel;
    private javax.swing.JLabel rendahLabel;
    private javax.swing.JLabel sedangLabel;
    private javax.swing.JLabel tinggiLabel;
    private javax.swing.JButton tutupButton;
    // End of variables declaration//GEN-END:variables

}
